---
#- hosts: Logstash1_clone
#  gather_facts: no

#  tasks:
#  - name: Validate logstash Version
#    fail: msg="Invalid ELK Version"
#    when: elk_version is undefined or not elk_version is match("\d+\.\d+\.\d+")

#  - name: Get logstash current version
#    command: rpm -q /usr/share/logstash/bin# ./logstash --qf %{VERSION}
#    args:
#      warn: no
#    changed_when: False
#    register: version_found

#  - name: Pre-download logstash install package
#    yum:
#      name: logstash-{{ elk_version }}
#      download_only: yes
#    when: version_found.stdout is version_compare(elk_version, '<')
- hosts: elasticsearch
  gather_facts: no

  # vars:
  #   s3_plugin_url: https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-{{ elk_version }}.zip

  tasks:
  - name: Validate elasticsearch Version
    fail: msg="Invalid ELK Version"
    when: elk_version is undefined or not elk_version is match("\d+\.\d+\.\d+")

  - name: Get elasticsearch current version
    command: rpm -q elasticsearch --qf %{VERSION}
    args:
      warn: no
    changed_when: False
    register: version_found

  - name: Pre-download elasticsearch install package
    yum:
      name: elasticsearch-{{ elk_version }}
      download_only: yes
    when: version_found.stdout is version_compare(elk_version, '<')
