---
- hosts: Logstash1_clone
  gather_facts: no

  tasks:
  - name: Validate logstash Version
    fail: msg="Invalid ELK Version"
    when: elk_version is undefined or not elk_version is match("\d+\.\d+\.\d+")
  - name: Get logstash current version
    command:
         cmd: dpkg-query --show logstash
    #command:
     #    cmd: /usr/share/logstash/bin/logstash --version
    args:
      warn: no
    changed_when: False
    register: version_found
  - name: getversion
    debug:
      var: version_found.stdout
  
  #- name: Pre-download logstash install package
   # yum:
    #  name: logstash-{{ elk_version }}
     # download_only: yes
    #when: version_found.stdout is version_compare(elk_version, '<')

