---
- hosts: Logstash1_clone
  #gather_facts: no

  tasks:
  - name: Validate logstash Version
    fail: msg="Invalid ELK Version"
    when: elk_version is undefined or not elk_version is match("\d+\.\d+\.\d+")
  - name: Task name
    stat:
      path: /usr/share/nano
    register: register_name
  - name: Task name2
    debug:
      msg: "The file or directory exists"
    when: register_name.stat.exists
  - name: Task name3
    debug:
      msg: "The file or directory not exists"
    when: not register_name.stat.exists
  #- name: Get logstash current version
    # command: rpm -q logstash --qf %{VERSION}
    #command: 
     #     cmd: dpkg -s logstash 
    #command:
     #    cmd: /usr/share/logstash/bin/logstash --version
    #args:
    #  warn: no
   # changed_when: False


  - name: Pre-download logstash install package
    yum:
      name: logstash-{{ elk_version }}
      download_only: yes
    when: version_found.stdout is version_compare(elk_version, '<')

